travis:
  secure:
    BINSTAR_TOKEN: fwvGkS4tkQuFmlR6uWX/oHHAA4+XCfgMRU+vzBzyhG43AArJCfeH+ynqjVuEIYXQFdSClDSH4YGI0RX0FUSF2b7bN80fHd9sHgSP6pYWBEp9Zh8Dc22Ugpj7r8H4FASppAunCkm0YicuVzCFmRbmfc9RN6tp/5NUiOdGawejQSFvcROqcpf8GdGnEPaCZXcv/9iZiwSFlOFqeTcnpH8YP5KZxlQV71fHo+gkAjFbhqj/eTDYN5bRp1EgpqVfLe9XkzoBhGMbU7+TGm4TIz6+lvk+cUqWSU78CoBdlHGDTqsmPlzmnKApdFm+pW8vrMBTqrrtKDrWo9c45SJDW3i74DAcMKzJrG4Vj2+ML00cLI9q/ufYuQvXz3TGZaUY4XjMclPADeDN/Umw8Mt6O9scdMJIGCjifVNqwaEMAAZ9iuJuYpm3LxEYYgg85g9UtvdxpXcDaTXerfEKz5BWY6ls4ZBR1auezajuRYYvK1DEhoGlJmcJUg9AnhJBurZskHIzOmEgJ5WbI6qaojHYFLFbOZuieDx2wJm8h+NxAcIMqmaPI9kXfWR07CJhe2qthe7DeOsCZtT3g+8H9iwmhatVUAZ1aAJbvHCHeLabTE+9V/NBHyQSg+dJICQXlbqQVkYo0eJNFF8fFGys69BdradKlJ/6mTyTedGLiEMJaCheyh8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
